services:
  - type: web
    name: el-patron-hn
    runtime: docker
    repo: https://github.com/leotechsistemas/ElpatronHN
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: el-patron-hn
          property: host
        format: https://${HOST},http://localhost:3002
      - key: DATABASE_URL
        fromDatabase:
          name: patron-erp-db
          property: connectionString

databases:
  - name: patron-erp-db
    databaseName: patron_erp
    plan: free
